#!/bin/bash
echo "=========================================="
echo "📋 GitHub 发布 - 复制粘贴命令集合"
echo "=========================================="
echo ""
echo "🔐 第一步：登录 GitHub"
echo "------------------------------------------"
echo "打开浏览器访问: https://github.com/login"
echo "输入用户名和密码登录"
echo ""
echo "📦 第二步：创建仓库"
echo "------------------------------------------"
echo "访问: https://github.com/new"
echo "填写:"
echo "  Repository name: model-auto-switch"
echo "  Description: AI 优化的自动切换模型技能"
echo "  不要勾选 'Initialize with README'"
echo "点击 'Create repository'"
echo ""
echo "⚙️  第三步：配置 Git (复制执行)"
echo "------------------------------------------"
echo "请告诉我你的 GitHub 用户名，然后执行:"
echo ""
echo "# 进入项目目录"
echo "cd /Users/a404/.openclaw/workspace/skills/model-auto-switch"
echo ""
echo "# 配置远程仓库 (替换 YOUR_USERNAME)"
echo "git remote add origin https://github.com/YOUR_USERNAME/model-auto-switch.git"
echo ""
echo "📤 第四步：推送代码 (复制执行)"
echo "------------------------------------------"
echo "# 推送主分支"
echo "git push -u origin main"
echo ""
echo "# 推送标签"
echo "git push origin --tags"
echo ""
echo "🎉 第五步：创建 Release"
echo "------------------------------------------"
echo "访问: https://github.com/YOUR_USERNAME/model-auto-switch/releases/new"
echo "选择标签: v3.1.0"
echo "标题: v3.1.0 - AI 优化的自动切换模型技能"
echo "描述: 复制 RELEASE_v3.1.0.md 的内容"
echo "点击 'Publish release'"
echo ""
echo "=========================================="
echo "🚀 完成！"
echo "=========================================="
echo ""
echo "📊 验证发布成功:"
echo "1. 访问你的仓库: https://github.com/YOUR_USERNAME/model-auto-switch"
echo "2. 检查 README.md 是否正确显示"
echo "3. 检查 Releases 页面是否有 v3.1.0"
echo ""
echo "🆘 需要帮助？告诉我具体问题！"