#!/bin/bash
# 最终发布脚本 - 简化版

set -e

echo "🚀 OpenClaw Model Balancer - 最终发布"
echo "=========================================="

cd "$(dirname "$0")"

# 显示当前状态
echo "📊 当前 Git 状态:"
git status --short | head -20

echo ""
echo "🏷️  当前标签:"
git tag -l | tail -5

echo ""
echo "📋 发布信息:"
echo "  版本: v3.1.0"
echo "  提交: $(git log -1 --pretty=format:'%H')"
echo "  时间: $(date '+%Y-%m-%d %H:%M:%S')"

echo ""
echo "=========================================="
echo "📝 发布步骤:"
echo ""
echo "1. 在 GitHub 创建新仓库:"
echo "   - 访问: https://github.com/new"
echo "   - 仓库名: openclaw-model-balancer"
echo "   - 描述: OpenClaw Model Balancer"
echo "   - 不初始化 README"
echo ""
echo "2. 配置远程仓库:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/openclaw-model-balancer.git"
echo ""
echo "3. 推送代码:"
echo "   git push -u origin main"
echo "   git push origin --tags"
echo ""
echo "4. 创建 Release:"
echo "   - 访问仓库的 Releases 页面"
echo "   - 点击 'Create a new release'"
echo "   - 选择标签 v3.1.0"
echo "   - 标题: v3.1.0 - OpenClaw Model Balancer"
echo "   - 描述: 复制 RELEASE_v3.1.0.md 内容"
echo "   - 发布!"
echo ""
echo "=========================================="
echo "🔒 安全提醒:"
echo ""
echo "✅ 已完成的检查:"
echo "   - 清理了临时文件"
echo "   - 检查了 API 密钥泄露"
echo "   - 验证了 .gitignore 配置"
echo ""
echo "⚠️  需要手动确认:"
echo "   - 确保不包含个人 API 密钥"
echo "   - 检查配置文件中的敏感信息"
echo "   - 验证日志文件不包含隐私数据"
echo ""
echo "=========================================="
echo "📁 重要文件:"
echo ""
echo "1. 发布说明: RELEASE_v3.1.0.md"
echo "2. 发布指南: GITHUB_RELEASE_INSTRUCTIONS.md"
echo "3. 用户指南: USER_GUIDE.md"
echo "4. 技能文档: SKILL.md"
echo "5. 测试报告: AI_OPTIMIZATION_TEST_REPORT.md"
echo ""
echo "=========================================="
echo "🎉 准备就绪！"
echo ""
echo "运行以下命令开始发布:"
echo ""
echo "# 1. 添加远程仓库 (替换 YOUR_USERNAME)"
echo "git remote add origin https://github.com/YOUR_USERNAME/openclaw-model-balancer.git"
echo ""
echo "# 2. 推送代码"
echo "git push -u origin main"
echo "git push origin --tags"
echo ""
echo "# 3. 访问 GitHub 完成发布"
echo "open https://github.com/YOUR_USERNAME/openclaw-model-balancer/releases/new"
echo ""
echo "=========================================="
echo "📞 如有问题，请参考:"
echo "   - GITHUB_RELEASE_INSTRUCTIONS.md (详细指南)"
echo "   - RELEASE_v3.1.0.md (发布说明)"
echo "   - 或联系技术支持"
echo ""
echo "🚀 祝您发布成功！"